### PR TITLE
overwrite with the gutil.PluginError code

### PR DESCRIPTION
**Pull request by shinnn**
ref. https://github.com/gulpjs/gulp/issues/360#issuecomment-115428815

Additionally, I renamed the package from `BetterError` to `bettererror`. According to [the npm docs](https://docs.npmjs.com/files/package.json#name):

> New packages must not have uppercase letters in the name.

### CODE REVIEW

**Comment by phated** [comment]
~~i vote for `better-error`~~ derp taken

**Comment by yocontra** [comment]
PluginError is a disaster in terms of behavior and API design. Many mistakes were made and now tears shed by many due to those mistakes. BetterError aims to be a replacement for PluginError, not a stand-in. The API and behavior are planned to be totally different and not make the same mistakes as PluginError.

**Comment by phated** [comment]
@contra can you speak to what still needs to happen in BetterError to make it a suitable replacement for PluginError?  I think it is the main thing holding gulp-util from complete deprecation.

**Comment by yocontra** [comment]
@phated Yeah I can write some docs on the desired API and tests to match when I have a minute

**Pull request closed without merging**
